version: '3.7'
volumes:
  data:
  capnp-secrets:
secrets:
  ocurrent-hub:
    external: true
  ocurrent-slack-endpoint:
    name: "base-builder-slack-endpoint-ci-firehose"
    external: true
  base-builder-oauth:
    external: true
  ocurrentbuilder-password:
    external: true
  base-image-builder-submission.cap:
    external: true
services:
  builder:
    image: ocurrent/base-images:live
    command: --confirm above-average --confirm-auto-release 120 --verbose --slack /run/secrets/ocurrent-slack-endpoint --capnp-address=base-images.ocamllabs.io:8101 --github-oauth /run/secrets/base-builder-oauth --submission-service /run/secrets/base-image-builder-submission.cap --staging-password-file /run/secrets/ocurrentbuilder-password
    init: true
    ports:
      - '8101:9000'
    environment:
      DOCKER_BUILDKIT: 0        # See https://github.com/moby/buildkit/issues/1105
      DEPLOYMENT: 1
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'ocurrentbuilder-password'
      - 'base-image-builder-submission.cap'
      - 'base-builder-oauth'
      - 'ocurrent-hub'
      - 'ocurrent-slack-endpoint'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
